theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: none
theme_advanced_buttons1 : "bold,italic,underline"
theme_advanced_buttons2 : ""
theme_advanced_buttons3 : ""
paste_text_sticky: true,
paste_text_sticky_default: true
plugins:
  - paste
